# Generated by Django 5.0.4 on 2024-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batuda',
            options={'verbose_name_plural': 'Batudes'},
        ),
        migrations.AddField(
            model_name='coto',
            name='short_code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coto',
            name='code',
            field=models.IntegerField(),
        ),
    ]
