# Generated by Django 5.0.4 on 2024-04-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batudes', '0005_alter_batuda_options_rename_data_batuda_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batuda',
            options={'ordering': ('-date', 'name'), 'verbose_name_plural': 'Batudes'},
        ),
        migrations.AlterField(
            model_name='batuda',
            name='coto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batudes.coto'),
        ),
    ]
