# Generated by Django 5.0.4 on 2024-04-17 08:03

import batudes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batudes', '0006_alter_batuda_options_alter_batuda_coto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batuda',
            name='coto',
            field=models.ForeignKey(default=batudes.models.get_default_coto_status, on_delete=django.db.models.deletion.CASCADE, to='batudes.coto'),
        ),
    ]
