# Generated by Django 5.0.4 on 2024-04-17 13:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batudes', '0007_alter_batuda_coto'),
    ]

    operations = [
        migrations.AddField(
            model_name='coto',
            name='bbox',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coto',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
